package codegen

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"io/ioutil"
	"sort"

	"github.com/pkg/errors"
)

func Output(ctx *GenContext, filePath string) error {
	if ctx.PackageName == "" {
		return errors.New("missing package name")
	}

	var unformatted bytes.Buffer
	fmt.Fprint(&unformatted, "// Code generated by go-codegen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&unformatted, "package %s\n", ctx.PackageName)
	outputImports(ctx, &unformatted)
	for _, g := range ctx.Generated {
		fmt.Fprintln(&unformatted, g)
	}

	// Parsing and printing ensures formatting.
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, unformatted.Bytes(), parser.ParseComments)
	if err != nil {
		fmt.Println(unformatted.String())
		return errors.Wrap(err, "parsing generated code")
	}

	var formatted bytes.Buffer
	printer.Fprint(&formatted, fset, file)
	return ioutil.WriteFile(filePath, formatted.Bytes(), 0644)
}

func outputImports(ctx *GenContext, w io.Writer) {
	if len(ctx.Imports) == 0 {
		return
	}

	fmt.Fprint(w, "import (\n")

	imports := make([]string, len(ctx.Imports))
	i := 0
	for k := range ctx.Imports {
		imports[i] = k
		i++
	}
	sort.Strings(imports)

	for _, i := range imports {
		fmt.Fprintf(w, "\t\"%s\"\n", i)
	}
	fmt.Fprint(w, ")\n")

}
